"""Full English, bug-bounty style Markdown report.

For every finding it explains: what the bug is, what the company risks if it
is not fixed, how a criminal could exploit it, and how to remediate it.
"""

from __future__ import annotations

from datetime import datetime
from typing import List

from zhack.core.models import Severity, TargetResult
from zhack.reporting.en_advisories import advisory_for

_SEV_EN = {
    Severity.CRITICAL: "CRITICAL",
    Severity.HIGH: "HIGH",
    Severity.MEDIUM: "MEDIUM",
    Severity.LOW: "LOW",
    Severity.INFO: "INFO",
}
_SEV_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]


def _clean(text: object) -> str:
    return " ".join(str(text or "").split())


def _summary_table(results: List[TargetResult]) -> str:
    counts = {sev: 0 for sev in _SEV_ORDER}
    for r in results:
        for f in r.findings:
            counts[f.severity] += 1
    lines = ["| Severity | Findings |", "| --- | ---: |"]
    for sev in _SEV_ORDER:
        lines.append(f"| {_SEV_EN[sev]} | {counts[sev]} |")
    return "\n".join(lines)


def build_en_markdown(results: List[TargetResult], generated: str = "") -> str:
    """Construye el reporte completo en inglés (formato bug bounty) en Markdown."""
    generated = generated or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total_findings = sum(len(r.findings) for r in results)
    worst = max(
        (f.severity for r in results for f in r.findings),
        key=lambda s: s.score,
        default=None,
    )

    parts: List[str] = [
        "# ZHack Security Assessment Report",
        "",
        f"- **Generated:** {generated}",
        f"- **Targets assessed:** {len(results)}",
        f"- **Total findings:** {total_findings}",
        f"- **Highest severity:** {_SEV_EN[worst] if worst else 'NONE'}",
        "- **Method:** read-only, non-destructive testing (GET/HEAD/OPTIONS). "
        "No state-changing requests were performed.",
        "",
        "> This report is intended for the asset owner. Each finding explains the bug, "
        "the business risk of not fixing it, a high-level example of how a criminal could "
        "exploit it, and the recommended remediation.",
        "",
        "## Executive summary",
        "",
        _summary_table(results),
        "",
        "## Findings",
    ]

    ordered = sorted(
        results,
        key=lambda r: (r.max_severity.score if r.max_severity else 0),
        reverse=True,
    )
    counter = 0
    for r in ordered:
        findings = sorted(r.findings, key=lambda f: f.severity.score, reverse=True)
        if not findings and not r.errors:
            continue
        parts.append("")
        parts.append(f"### Target: {r.url}")
        if r.status:
            parts.append(f"\nHTTP status: {r.status}")
        for err in r.errors[:5]:
            parts.append(f"\n> Scan error: {_clean(err)}")
        for f in findings:
            counter += 1
            adv = advisory_for(f.check, f.title)
            parts.extend(
                [
                    "",
                    "---",
                    "",
                    f"#### ZH-{counter:03d} · {adv.title} — {_SEV_EN[f.severity]}",
                    "",
                    f"- **Affected asset:** {f.url or r.url}",
                    f"- **Check:** `{f.check}`",
                    f"- **Scanner title:** {_clean(f.title)}",
                ]
            )
            if f.evidence:
                parts.append(f"- **Evidence:** `{_clean(f.evidence)}`")
            parts.extend(
                [
                    "",
                    "**What is the bug?**",
                    "",
                    _clean(adv.description),
                    "",
                    "**What the company risks if it is not fixed**",
                    "",
                    _clean(adv.business_risk),
                    "",
                    "**How a criminal could exploit it**",
                    "",
                    _clean(adv.criminal_example),
                    "",
                    "**Recommended fix**",
                    "",
                    _clean(adv.remediation),
                ]
            )
            if adv.references:
                parts.extend(
                    [
                        "",
                        "**References:** " + " · ".join(adv.references),
                    ]
                )

    parts.extend(
        [
            "",
            "---",
            "",
            "*Generated by ZHack — a defensive scanner. All tests were read-only and "
            "performed against owned or explicitly authorized assets.*",
            "",
        ]
    )
    return "\n".join(parts)


def write_en_report(results: List[TargetResult], path: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(build_en_markdown(results))
